[package]
name = "rust_nuggets_basics"
version = "0.1.0"
authors = ["Eric Seppanen <eds@reric.net>"]
edition = "2018"

[[example]]
name = "enums"
crate-type = ["lib"]

[[example]]
name = "structs"
crate-type = ["lib"]

[[example]]
name = "standard"
crate-type = ["lib"]

[dependencies]
