#!/bin/bash

echo "######## $TITLE ########"
echo "https://github.com/ericseppanen/rust-nuggets"
for FILE in ../warnings/examples/*.rs ../errors/examples/*.rs; do
  FILE1=${FILE%.rs}  # strip extension
  FILE2=${FILE1##*/} # strip path
  echo -e "\n\n\n\n$ cargo check --example $FILE2\n"
  cargo -q --color always check --example $FILE2
done
